# Generated by Django 3.1.5 on 2021-01-09 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Marki',
            },
        ),
        migrations.CreateModel(
            name='ModelButa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('marka', models.ForeignKey(limit_choices_to={'marka': 'self'}, on_delete=django.db.models.deletion.PROTECT, related_name='model_buta', to='magazyn.marka')),
            ],
            options={
                'verbose_name_plural': 'Modele',
            },
        ),
        migrations.CreateModel(
            name='Buty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=50)),
                ('kolor', models.CharField(max_length=50)),
                ('rozmiar', models.CharField(choices=[('35', '35'), ('35 1/3', '35 1/3'), ('35 1/2', '35 1/2'), ('35 2/3', '35 2/3'), ('36', '36'), ('36 1/3', '36 1/3'), ('36 1/2', '36 1/2'), ('36 2/3', '36 2/3'), ('37', '37'), ('37 1/3', '37 1/3'), ('37 1/2', '37 1/2'), ('37 2/3', '37 2/3'), ('38', '38'), ('38 1/3', '38 1/3'), ('38 1/2', '38 1/2'), ('38 2/3', '38 2/3'), ('39', '39'), ('39 1/3', '39 1/3'), ('39 1/2', '39 1/2'), ('39 2/3', '39 2/3'), ('40', '40'), ('40 1/3', '40 1/3'), ('40 1/2', '40 1/2'), ('40 2/3', '40 2/3'), ('41', '41'), ('41 1/3', '41 1/3'), ('41 1/2', '41 1/2'), ('41 2/3', '41 2/3'), ('42', '42'), ('42 1/3', '42 1/3'), ('42 1/2', '42 1/2'), ('42 2/3', '42 2/3'), ('43', '43'), ('43 1/3', '43 1/3'), ('43 1/2', '43 1/2'), ('43 2/3', '43 2/3'), ('44', '44'), ('44 1/3', '44 1/3'), ('44 1/2', '44 1/2'), ('44 2/3', '44 2/3'), ('45', '45'), ('45 1/3', '45 1/3'), ('45 1/2', '45 1/2'), ('45 2/3', '45 2/3'), ('46', '46'), ('46 1/3', '46 1/3'), ('46 1/2', '46 1/2'), ('46 2/3', '46 2/3'), ('47', '47'), ('47 1/3', '47 1/3'), ('47 1/2', '47 1/2'), ('47 2/3', '47 2/3'), ('48', '48'), ('48 1/3', '48 1/3'), ('48 1/2', '48 1/2'), ('48 2/3', '48 2/3')], max_length=7)),
                ('data_zakupu', models.DateField(null=True)),
                ('cena_zakupu', models.DecimalField(decimal_places=2, max_digits=8)),
                ('szacowana_wartosc', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('uwagi', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('w magazynie', 'W magazynie'), ('sprzedano', 'Sprzedano'), ('zwrot', 'Zwrot')], max_length=200)),
                ('gdzie_kupione', models.CharField(max_length=50, null=True)),
                ('data_sprzedazy', models.DateField(blank=True, null=True)),
                ('cena_sprzedazy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazyn.marka')),
                ('model_buta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazyn.modelbuta')),
            ],
            options={
                'verbose_name_plural': 'Buty',
            },
        ),
    ]
