# Generated by Django 3.1.5 on 2021-01-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbuta',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_buta', to='magazyn.marka'),
        ),
    ]
