# Generated by Django 3.1.5 on 2021-01-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0002_auto_20210109_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buty',
            name='model_buta',
            field=models.ForeignKey(limit_choices_to={'marka': None}, on_delete=django.db.models.deletion.PROTECT, to='magazyn.modelbuta'),
        ),
        migrations.AlterField(
            model_name='modelbuta',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_buta', to='magazyn.marka', to_field='name'),
        ),
    ]
