# Generated by Django 3.1.5 on 2021-01-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0004_auto_20210109_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buty',
            options={'permissions': [('magazyn_admin', 'User can do everything in Magazyn app')], 'verbose_name_plural': 'Buty'},
        ),
    ]
