# Generated by Django 3.1.5 on 2021-01-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0006_remove_buty_kolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprzedane',
            fields=[
                ('buty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='magazyn.buty')),
                ('data_sprzedazy', models.DateField(blank=True, null=True)),
                ('cena_sprzedazy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name_plural': 'Buty',
                'permissions': [('magazyn_admin', 'User can do everything in Magazyn app')],
            },
        ),
        migrations.RemoveField(
            model_name='buty',
            name='cena_sprzedazy',
        ),
        migrations.RemoveField(
            model_name='buty',
            name='data_sprzedazy',
        ),
    ]
