# Generated by Django 3.1.5 on 2021-01-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0008_auto_20210115_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprzedane',
            options={'verbose_name_plural': 'Sprzedane'},
        ),
    ]
