# Generated by Django 3.1.5 on 2021-01-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0009_auto_20210115_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzedane',
            name='data_przesylki',
            field=models.DateField(blank=True, null=True, verbose_name='data przesyłki'),
        ),
        migrations.AddField(
            model_name='sprzedane',
            name='komu_sprzedane',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sprzedane',
            name='sledzenie_przesylki',
            field=models.URLField(blank=True, null=True, verbose_name='Link do śledzenia przesyłki'),
        ),
        migrations.AddField(
            model_name='sprzedane',
            name='wplynely_pieniadze',
            field=models.BooleanField(choices=[(True, 'Tak'), (False, 'Nie')], default=False, verbose_name='Wpłynęły pieniądze'),
        ),
    ]
