# Generated by Django 3.1.5 on 2021-01-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0010_auto_20210115_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprzedane',
            options={'ordering': ['buty'], 'verbose_name_plural': 'Sprzedane'},
        ),
    ]
