# Generated by Django 3.1.5 on 2021-01-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0011_auto_20210115_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprzedane',
            name='data_przesylki',
            field=models.DateField(blank=True, null=True, verbose_name='Data przesyłki'),
        ),
    ]
