# Generated by Django 3.1.5 on 2021-01-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0012_auto_20210115_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprzedane',
            options={'verbose_name_plural': 'Sprzedane'},
        ),
    ]
