# Generated by Django 3.1.5 on 2021-01-15 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0013_auto_20210115_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zwrot',
            fields=[
                ('wplynely_pieniadze', models.BooleanField(choices=[(True, 'Tak'), (False, 'Nie')], default=False, verbose_name='Wpłynęły pieniądze')),
                ('data_przesylki', models.DateField(blank=True, null=True, verbose_name='Data przesyłki')),
                ('sledzenie_przesylki', models.URLField(blank=True, null=True, verbose_name='Link do śledzenia przesyłki')),
                ('buty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='magazyn.buty')),
                ('data_zwrotu', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Zwrot',
            },
        ),
    ]
